import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Wrapper from "./Wrapper"; 
import QueryProvider from './QueryProvider';
import { Toaster } from "react-hot-toast";
import {ReactQueryDevtools} from "@tanstack/react-query-devtools"; 


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <Wrapper>{children}</Wrapper>
          <Toaster position="top-right" reverseOrder={false} />
          <ReactQueryDevtools initialIsOpen={false}/>
        </QueryProvider>
        
      </body>
    </html>
  );
}
